const KEY="becoming_stan_drafts";
async function getArticles(){try{const r=await fetch("articles.json");const base=await r.json();return [...JSON.parse(localStorage.getItem(KEY)||"[]"),...base]}catch{return JSON.parse(localStorage.getItem(KEY)||"[]")}}
const esc=s=>(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function card(a){return `<a class="story-card" href="article.html?id=${encodeURIComponent(a.id)}"><div class="image" ${a.image?`style="background-image:url('${esc(a.image)}')"`:""}></div><div class="meta">${esc(a.category)} · ${esc(a.date)}</div><h2>${esc(a.title)}</h2><p>${esc(a.excerpt)}</p></a>`}
(async()=>{const articles=await getArticles();
const latest=document.querySelector("#latest");if(latest){articles.sort((a,b)=>b.date.localeCompare(a.date));latest.innerHTML=articles.map(card).join("");document.querySelector("#count").textContent=articles.length+" stories"}
const ct=document.querySelector("#category-title");if(ct){const n=new URLSearchParams(location.search).get("cat")||"All stories";ct.textContent=n;const f=articles.filter(a=>n==="All stories"||a.category===n);document.querySelector("#category-stories").innerHTML=f.length?f.map(card).join(""):"<p>No stories yet.</p>"}
const at=document.querySelector("#article-title");if(at){const a=articles.find(x=>x.id===new URLSearchParams(location.search).get("id"));if(!a){at.textContent="Story not found";return}document.title=a.title+" — Becoming, by Stan";document.querySelector("#article-category").textContent=a.category;at.textContent=a.title;document.querySelector("#article-subtitle").textContent=a.subtitle||"";document.querySelector("#article-meta").textContent=a.date;if(a.image)document.querySelector("#article-image").innerHTML=`<img class="article-hero" src="${esc(a.image)}" alt="">`;document.querySelector("#article-body").innerHTML=a.body||""}
const form=document.querySelector("#story-form");if(form){date.value=new Date().toISOString().slice(0,10);renderDrafts();form.onsubmit=e=>{e.preventDefault();const a={id:"local-"+Date.now(),title:title.value,subtitle:subtitle.value,category:category.value,image:image.value,date:date.value,excerpt:excerpt.value,body:body.value};const d=JSON.parse(localStorage.getItem(KEY)||"[]");d.unshift(a);localStorage.setItem(KEY,JSON.stringify(d));form.reset();date.value=new Date().toISOString().slice(0,10);renderDrafts();alert("Story saved in this browser.")}}})();
function renderDrafts(){const el=document.querySelector("#drafts");if(!el)return;const d=JSON.parse(localStorage.getItem(KEY)||"[]");el.innerHTML=d.length?d.map(a=>`<div class="draft"><span><b>${esc(a.title)}</b><br><small>${esc(a.category)} · ${esc(a.date)}</small></span><button onclick="deleteDraft('${a.id}')">Delete</button></div>`).join(""):"<p>No browser stories yet.</p>"}function deleteDraft(id){const d=JSON.parse(localStorage.getItem(KEY)||"[]").filter(a=>a.id!==id);localStorage.setItem(KEY,JSON.stringify(d));renderDrafts()}
